/*
BeeOS OpenAPI (user contract)

Testing TasksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package beeos

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/beeos-ai/sdk-go"
)

func Test_beeos_TasksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TasksAPIService CancelTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.CancelTask(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService ContinueTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.ContinueTask(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService CreateTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.TasksAPI.CreateTask(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService DeleteTaskWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string
		var webhookId string

		httpRes, err := apiClient.TasksAPI.DeleteTaskWebhook(context.Background(), agentId, taskId, webhookId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService GetTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.GetTask(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService ListAgentTasks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.TasksAPI.ListAgentTasks(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService ListTaskMessages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.ListTaskMessages(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService ListTaskWebhooks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.ListTaskWebhooks(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService ListUserTasks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TasksAPI.ListUserTasks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService ListWebhookDeliveries", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string
		var webhookId string

		resp, httpRes, err := apiClient.TasksAPI.ListWebhookDeliveries(context.Background(), agentId, taskId, webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService RedeliverWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string
		var webhookId string
		var deliveryId string

		resp, httpRes, err := apiClient.TasksAPI.RedeliverWebhook(context.Background(), agentId, taskId, webhookId, deliveryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService RegisterTaskWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.RegisterTaskWebhook(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TasksAPIService StreamTaskEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var taskId string

		resp, httpRes, err := apiClient.TasksAPI.StreamTaskEvents(context.Background(), agentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
