/*
BeeOS OpenAPI (user contract)

Testing ConversationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package beeos

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/beeos-ai/sdk-go"
)

func Test_beeos_ConversationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConversationsAPIService CancelConversation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var conversationId string

		resp, httpRes, err := apiClient.ConversationsAPI.CancelConversation(context.Background(), agentId, conversationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService ClearConversation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var conversationId string

		resp, httpRes, err := apiClient.ConversationsAPI.ClearConversation(context.Background(), agentId, conversationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService CreateConversation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.ConversationsAPI.CreateConversation(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService DeleteConversation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var convId string

		httpRes, err := apiClient.ConversationsAPI.DeleteConversation(context.Background(), agentId, convId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService GetConversation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var convId string

		resp, httpRes, err := apiClient.ConversationsAPI.GetConversation(context.Background(), agentId, convId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService ListConversationMessages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var convId string

		resp, httpRes, err := apiClient.ConversationsAPI.ListConversationMessages(context.Background(), agentId, convId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService ListConversations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.ConversationsAPI.ListConversations(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService RenameConversation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var convId string

		resp, httpRes, err := apiClient.ConversationsAPI.RenameConversation(context.Background(), agentId, convId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService SendConversationMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var convId string

		resp, httpRes, err := apiClient.ConversationsAPI.SendConversationMessage(context.Background(), agentId, convId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService SetConversationModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var conversationId string

		httpRes, err := apiClient.ConversationsAPI.SetConversationModel(context.Background(), agentId, conversationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConversationsAPIService StreamConversationEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var convId string

		resp, httpRes, err := apiClient.ConversationsAPI.StreamConversationEvents(context.Background(), agentId, convId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
