/*
BeeOS OpenAPI (user contract)

The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beeos

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentListResponse{}

// AgentListResponse struct for AgentListResponse
type AgentListResponse struct {
	Success bool `json:"success"`
	Data []AgentDTO `json:"data"`
	Total int64 `json:"total"`
}

type _AgentListResponse AgentListResponse

// NewAgentListResponse instantiates a new AgentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentListResponse(success bool, data []AgentDTO, total int64) *AgentListResponse {
	this := AgentListResponse{}
	this.Success = success
	this.Data = data
	this.Total = total
	return &this
}

// NewAgentListResponseWithDefaults instantiates a new AgentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentListResponseWithDefaults() *AgentListResponse {
	this := AgentListResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *AgentListResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *AgentListResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *AgentListResponse) GetData() []AgentDTO {
	if o == nil {
		var ret []AgentDTO
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetDataOk() ([]AgentDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AgentListResponse) SetData(v []AgentDTO) {
	o.Data = v
}

// GetTotal returns the Total field value
func (o *AgentListResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AgentListResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AgentListResponse) SetTotal(v int64) {
	o.Total = v
}

func (o AgentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *AgentListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentListResponse := _AgentListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentListResponse)

	if err != nil {
		return err
	}

	*o = AgentListResponse(varAgentListResponse)

	return err
}

type NullableAgentListResponse struct {
	value *AgentListResponse
	isSet bool
}

func (v NullableAgentListResponse) Get() *AgentListResponse {
	return v.value
}

func (v *NullableAgentListResponse) Set(val *AgentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentListResponse(val *AgentListResponse) *NullableAgentListResponse {
	return &NullableAgentListResponse{value: val, isSet: true}
}

func (v NullableAgentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


