/*
BeeOS OpenAPI (user contract)

The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beeos

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StringResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StringResponse{}

// StringResponse struct for StringResponse
type StringResponse struct {
	Success bool `json:"success"`
	Data string `json:"data"`
}

type _StringResponse StringResponse

// NewStringResponse instantiates a new StringResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStringResponse(success bool, data string) *StringResponse {
	this := StringResponse{}
	this.Success = success
	this.Data = data
	return &this
}

// NewStringResponseWithDefaults instantiates a new StringResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStringResponseWithDefaults() *StringResponse {
	this := StringResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *StringResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *StringResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *StringResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *StringResponse) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *StringResponse) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *StringResponse) SetData(v string) {
	o.Data = v
}

func (o StringResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StringResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *StringResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStringResponse := _StringResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStringResponse)

	if err != nil {
		return err
	}

	*o = StringResponse(varStringResponse)

	return err
}

type NullableStringResponse struct {
	value *StringResponse
	isSet bool
}

func (v NullableStringResponse) Get() *StringResponse {
	return v.value
}

func (v *NullableStringResponse) Set(val *StringResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStringResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStringResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStringResponse(val *StringResponse) *NullableStringResponse {
	return &NullableStringResponse{value: val, isSet: true}
}

func (v NullableStringResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStringResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


