/*
BeeOS OpenAPI (user contract)

The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beeos

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeployInstanceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployInstanceRequest{}

// DeployInstanceRequest Either supply a **catalog** `variantId` (authoritative — lifts `agentFramework` / `providerId` / region / scheduling hints from the variant) **or** provide an explicit `agentFramework` (+ optional `providerId`). Client-supplied scheduling fields (ownershipPreference / maxPricePerHour / resourceTypeHint) are **not** accepted here; the catalog variant is the source of truth. 
type DeployInstanceRequest struct {
	VariantId *string `json:"variantId,omitempty"`
	AgentFramework *string `json:"agentFramework,omitempty"`
	ProviderId *string `json:"providerId,omitempty"`
	// Free-form provider-specific configuration merged with the catalog config (catalog wins on key conflicts). 
	ProviderConfig map[string]interface{} `json:"providerConfig,omitempty"`
	Name string `json:"name"`
	ModelPrimary *string `json:"modelPrimary,omitempty"`
	Models []string `json:"models,omitempty"`
	SystemPrompt *string `json:"systemPrompt,omitempty"`
	McpServers map[string]interface{} `json:"mcpServers,omitempty"`
	BridgeId *string `json:"bridgeId,omitempty"`
	// Alternate name for `providerConfig`; same semantics. Used by the variant-driven path to layer user extras (apiKeys / apiBaseUrls) on top of the catalog config. 
	Config map[string]interface{} `json:"config,omitempty"`
	ClusterId *string `json:"clusterId,omitempty"`
	PreferredRegion *string `json:"preferredRegion,omitempty"`
}

type _DeployInstanceRequest DeployInstanceRequest

// NewDeployInstanceRequest instantiates a new DeployInstanceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployInstanceRequest(name string) *DeployInstanceRequest {
	this := DeployInstanceRequest{}
	this.Name = name
	return &this
}

// NewDeployInstanceRequestWithDefaults instantiates a new DeployInstanceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployInstanceRequestWithDefaults() *DeployInstanceRequest {
	this := DeployInstanceRequest{}
	return &this
}

// GetVariantId returns the VariantId field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetVariantId() string {
	if o == nil || IsNil(o.VariantId) {
		var ret string
		return ret
	}
	return *o.VariantId
}

// GetVariantIdOk returns a tuple with the VariantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetVariantIdOk() (*string, bool) {
	if o == nil || IsNil(o.VariantId) {
		return nil, false
	}
	return o.VariantId, true
}

// HasVariantId returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasVariantId() bool {
	if o != nil && !IsNil(o.VariantId) {
		return true
	}

	return false
}

// SetVariantId gets a reference to the given string and assigns it to the VariantId field.
func (o *DeployInstanceRequest) SetVariantId(v string) {
	o.VariantId = &v
}

// GetAgentFramework returns the AgentFramework field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetAgentFramework() string {
	if o == nil || IsNil(o.AgentFramework) {
		var ret string
		return ret
	}
	return *o.AgentFramework
}

// GetAgentFrameworkOk returns a tuple with the AgentFramework field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetAgentFrameworkOk() (*string, bool) {
	if o == nil || IsNil(o.AgentFramework) {
		return nil, false
	}
	return o.AgentFramework, true
}

// HasAgentFramework returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasAgentFramework() bool {
	if o != nil && !IsNil(o.AgentFramework) {
		return true
	}

	return false
}

// SetAgentFramework gets a reference to the given string and assigns it to the AgentFramework field.
func (o *DeployInstanceRequest) SetAgentFramework(v string) {
	o.AgentFramework = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId) {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *DeployInstanceRequest) SetProviderId(v string) {
	o.ProviderId = &v
}

// GetProviderConfig returns the ProviderConfig field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetProviderConfig() map[string]interface{} {
	if o == nil || IsNil(o.ProviderConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.ProviderConfig
}

// GetProviderConfigOk returns a tuple with the ProviderConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetProviderConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ProviderConfig) {
		return map[string]interface{}{}, false
	}
	return o.ProviderConfig, true
}

// HasProviderConfig returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasProviderConfig() bool {
	if o != nil && !IsNil(o.ProviderConfig) {
		return true
	}

	return false
}

// SetProviderConfig gets a reference to the given map[string]interface{} and assigns it to the ProviderConfig field.
func (o *DeployInstanceRequest) SetProviderConfig(v map[string]interface{}) {
	o.ProviderConfig = v
}

// GetName returns the Name field value
func (o *DeployInstanceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeployInstanceRequest) SetName(v string) {
	o.Name = v
}

// GetModelPrimary returns the ModelPrimary field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetModelPrimary() string {
	if o == nil || IsNil(o.ModelPrimary) {
		var ret string
		return ret
	}
	return *o.ModelPrimary
}

// GetModelPrimaryOk returns a tuple with the ModelPrimary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetModelPrimaryOk() (*string, bool) {
	if o == nil || IsNil(o.ModelPrimary) {
		return nil, false
	}
	return o.ModelPrimary, true
}

// HasModelPrimary returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasModelPrimary() bool {
	if o != nil && !IsNil(o.ModelPrimary) {
		return true
	}

	return false
}

// SetModelPrimary gets a reference to the given string and assigns it to the ModelPrimary field.
func (o *DeployInstanceRequest) SetModelPrimary(v string) {
	o.ModelPrimary = &v
}

// GetModels returns the Models field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetModels() []string {
	if o == nil || IsNil(o.Models) {
		var ret []string
		return ret
	}
	return o.Models
}

// GetModelsOk returns a tuple with the Models field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Models) {
		return nil, false
	}
	return o.Models, true
}

// HasModels returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasModels() bool {
	if o != nil && !IsNil(o.Models) {
		return true
	}

	return false
}

// SetModels gets a reference to the given []string and assigns it to the Models field.
func (o *DeployInstanceRequest) SetModels(v []string) {
	o.Models = v
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt) {
		var ret string
		return ret
	}
	return *o.SystemPrompt
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetSystemPromptOk() (*string, bool) {
	if o == nil || IsNil(o.SystemPrompt) {
		return nil, false
	}
	return o.SystemPrompt, true
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasSystemPrompt() bool {
	if o != nil && !IsNil(o.SystemPrompt) {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given string and assigns it to the SystemPrompt field.
func (o *DeployInstanceRequest) SetSystemPrompt(v string) {
	o.SystemPrompt = &v
}

// GetMcpServers returns the McpServers field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetMcpServers() map[string]interface{} {
	if o == nil || IsNil(o.McpServers) {
		var ret map[string]interface{}
		return ret
	}
	return o.McpServers
}

// GetMcpServersOk returns a tuple with the McpServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetMcpServersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.McpServers) {
		return map[string]interface{}{}, false
	}
	return o.McpServers, true
}

// HasMcpServers returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasMcpServers() bool {
	if o != nil && !IsNil(o.McpServers) {
		return true
	}

	return false
}

// SetMcpServers gets a reference to the given map[string]interface{} and assigns it to the McpServers field.
func (o *DeployInstanceRequest) SetMcpServers(v map[string]interface{}) {
	o.McpServers = v
}

// GetBridgeId returns the BridgeId field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetBridgeId() string {
	if o == nil || IsNil(o.BridgeId) {
		var ret string
		return ret
	}
	return *o.BridgeId
}

// GetBridgeIdOk returns a tuple with the BridgeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetBridgeIdOk() (*string, bool) {
	if o == nil || IsNil(o.BridgeId) {
		return nil, false
	}
	return o.BridgeId, true
}

// HasBridgeId returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasBridgeId() bool {
	if o != nil && !IsNil(o.BridgeId) {
		return true
	}

	return false
}

// SetBridgeId gets a reference to the given string and assigns it to the BridgeId field.
func (o *DeployInstanceRequest) SetBridgeId(v string) {
	o.BridgeId = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *DeployInstanceRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetClusterId() string {
	if o == nil || IsNil(o.ClusterId) {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetClusterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *DeployInstanceRequest) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetPreferredRegion returns the PreferredRegion field value if set, zero value otherwise.
func (o *DeployInstanceRequest) GetPreferredRegion() string {
	if o == nil || IsNil(o.PreferredRegion) {
		var ret string
		return ret
	}
	return *o.PreferredRegion
}

// GetPreferredRegionOk returns a tuple with the PreferredRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployInstanceRequest) GetPreferredRegionOk() (*string, bool) {
	if o == nil || IsNil(o.PreferredRegion) {
		return nil, false
	}
	return o.PreferredRegion, true
}

// HasPreferredRegion returns a boolean if a field has been set.
func (o *DeployInstanceRequest) HasPreferredRegion() bool {
	if o != nil && !IsNil(o.PreferredRegion) {
		return true
	}

	return false
}

// SetPreferredRegion gets a reference to the given string and assigns it to the PreferredRegion field.
func (o *DeployInstanceRequest) SetPreferredRegion(v string) {
	o.PreferredRegion = &v
}

func (o DeployInstanceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployInstanceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VariantId) {
		toSerialize["variantId"] = o.VariantId
	}
	if !IsNil(o.AgentFramework) {
		toSerialize["agentFramework"] = o.AgentFramework
	}
	if !IsNil(o.ProviderId) {
		toSerialize["providerId"] = o.ProviderId
	}
	if !IsNil(o.ProviderConfig) {
		toSerialize["providerConfig"] = o.ProviderConfig
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.ModelPrimary) {
		toSerialize["modelPrimary"] = o.ModelPrimary
	}
	if !IsNil(o.Models) {
		toSerialize["models"] = o.Models
	}
	if !IsNil(o.SystemPrompt) {
		toSerialize["systemPrompt"] = o.SystemPrompt
	}
	if !IsNil(o.McpServers) {
		toSerialize["mcpServers"] = o.McpServers
	}
	if !IsNil(o.BridgeId) {
		toSerialize["bridgeId"] = o.BridgeId
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.ClusterId) {
		toSerialize["clusterId"] = o.ClusterId
	}
	if !IsNil(o.PreferredRegion) {
		toSerialize["preferredRegion"] = o.PreferredRegion
	}
	return toSerialize, nil
}

func (o *DeployInstanceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeployInstanceRequest := _DeployInstanceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeployInstanceRequest)

	if err != nil {
		return err
	}

	*o = DeployInstanceRequest(varDeployInstanceRequest)

	return err
}

type NullableDeployInstanceRequest struct {
	value *DeployInstanceRequest
	isSet bool
}

func (v NullableDeployInstanceRequest) Get() *DeployInstanceRequest {
	return v.value
}

func (v *NullableDeployInstanceRequest) Set(val *DeployInstanceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployInstanceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployInstanceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployInstanceRequest(val *DeployInstanceRequest) *NullableDeployInstanceRequest {
	return &NullableDeployInstanceRequest{value: val, isSet: true}
}

func (v NullableDeployInstanceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployInstanceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


