/*
BeeOS OpenAPI (user contract)

The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beeos

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InvokeAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvokeAgentRequest{}

// InvokeAgentRequest struct for InvokeAgentRequest
type InvokeAgentRequest struct {
	// The message to send to the agent.
	Message string `json:"message"`
	// Optional conversation context ID for multi-turn conversations.
	ContextId *string `json:"context_id,omitempty"`
	// Timeout in milliseconds (default 120000).
	TimeoutMs *int64 `json:"timeout_ms,omitempty"`
}

type _InvokeAgentRequest InvokeAgentRequest

// NewInvokeAgentRequest instantiates a new InvokeAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvokeAgentRequest(message string) *InvokeAgentRequest {
	this := InvokeAgentRequest{}
	this.Message = message
	return &this
}

// NewInvokeAgentRequestWithDefaults instantiates a new InvokeAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvokeAgentRequestWithDefaults() *InvokeAgentRequest {
	this := InvokeAgentRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *InvokeAgentRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *InvokeAgentRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *InvokeAgentRequest) SetMessage(v string) {
	o.Message = v
}

// GetContextId returns the ContextId field value if set, zero value otherwise.
func (o *InvokeAgentRequest) GetContextId() string {
	if o == nil || IsNil(o.ContextId) {
		var ret string
		return ret
	}
	return *o.ContextId
}

// GetContextIdOk returns a tuple with the ContextId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvokeAgentRequest) GetContextIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContextId) {
		return nil, false
	}
	return o.ContextId, true
}

// HasContextId returns a boolean if a field has been set.
func (o *InvokeAgentRequest) HasContextId() bool {
	if o != nil && !IsNil(o.ContextId) {
		return true
	}

	return false
}

// SetContextId gets a reference to the given string and assigns it to the ContextId field.
func (o *InvokeAgentRequest) SetContextId(v string) {
	o.ContextId = &v
}

// GetTimeoutMs returns the TimeoutMs field value if set, zero value otherwise.
func (o *InvokeAgentRequest) GetTimeoutMs() int64 {
	if o == nil || IsNil(o.TimeoutMs) {
		var ret int64
		return ret
	}
	return *o.TimeoutMs
}

// GetTimeoutMsOk returns a tuple with the TimeoutMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvokeAgentRequest) GetTimeoutMsOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeoutMs) {
		return nil, false
	}
	return o.TimeoutMs, true
}

// HasTimeoutMs returns a boolean if a field has been set.
func (o *InvokeAgentRequest) HasTimeoutMs() bool {
	if o != nil && !IsNil(o.TimeoutMs) {
		return true
	}

	return false
}

// SetTimeoutMs gets a reference to the given int64 and assigns it to the TimeoutMs field.
func (o *InvokeAgentRequest) SetTimeoutMs(v int64) {
	o.TimeoutMs = &v
}

func (o InvokeAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvokeAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.ContextId) {
		toSerialize["context_id"] = o.ContextId
	}
	if !IsNil(o.TimeoutMs) {
		toSerialize["timeout_ms"] = o.TimeoutMs
	}
	return toSerialize, nil
}

func (o *InvokeAgentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvokeAgentRequest := _InvokeAgentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvokeAgentRequest)

	if err != nil {
		return err
	}

	*o = InvokeAgentRequest(varInvokeAgentRequest)

	return err
}

type NullableInvokeAgentRequest struct {
	value *InvokeAgentRequest
	isSet bool
}

func (v NullableInvokeAgentRequest) Get() *InvokeAgentRequest {
	return v.value
}

func (v *NullableInvokeAgentRequest) Set(val *InvokeAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInvokeAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInvokeAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvokeAgentRequest(val *InvokeAgentRequest) *NullableInvokeAgentRequest {
	return &NullableInvokeAgentRequest{value: val, isSet: true}
}

func (v NullableInvokeAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvokeAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


